### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by TanXi789** [j-morano/rrwnet#2]
Hello, why does the following error occur when I train the code?
(cup) H:\rrwnet-main\train>python train.py --dataset RITE-train --model RRWNet
[{'i': 0, 'train_path': '__training/Journal_paper/RITE-train/4_folds/RRWNet_5it_lr1e-04_RRLoss-BCE3Loss_bc64/0', 'train_imgs': [29, 40, 21, 37, 34, 35, 32, 27, 39, 26, 38, 28, 23, 31, 22], 'val_imgs': [33, 24, 36, 30, 25]}, {'i'
: 1, 'train_path': '__training/Journal_paper/RITE-train/4_folds/RRWNet_5it_lr1e-04_RRLoss-BCE3Loss_bc64/1', 'train_imgs': [33, 24, 36, 30, 25, 35, 32, 27, 39, 26, 38, 28, 23, 31, 22], 'val_imgs': [29, 40, 21, 37, 34]}, {'i': 2, 
'train_path': '__training/Journal_paper/RITE-train/4_folds/RRWNet_5it_lr1e-04_RRLoss-BCE3Loss_bc64/2', 'train_imgs': [33, 24, 36, 30, 25, 29, 40, 21, 37, 34, 38, 28, 23, 31, 22], 'val_imgs': [35, 32, 27, 39, 26]}, {'i': 3, 'trai
n_path': '__training/Journal_paper/RITE-train/4_folds/RRWNet_5it_lr1e-04_RRLoss-BCE3Loss_bc64/3', 'train_imgs': [33, 24, 36, 30, 25, 29, 40, 21, 37, 34, 35, 32, 27, 39, 26], 'val_imgs': [38, 28, 23, 31, 22]}]

 __training/Journal_paper/RITE-train/4_folds/RRWNet_5it_lr1e-04_RRLoss-BCE3Loss_bc64/0
[PID: 18132] TRAINING SET (0): [29, 40, 21, 37, 34, 35, 32, 27, 39, 26, 38, 28, 23, 31, 22]/[33, 24, 36, 30, 25]
retino: {}, type: <class 'dict'>
Process Process-1:
Traceback (most recent call last):
  File "D:\Anaconda\envs\cup\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Anaconda\envs\cup\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "H:\rrwnet-main\train\train.py", line 191, in train_sets
    train(
  File "H:\rrwnet-main\train\train.py", line 110, in train
    cnnet.training(
  File "H:\rrwnet-main\train\r2av.py", line 215, in training
    train_loss.append([self.iter] + self.train_epoch(train_loader))
  File "H:\rrwnet-main\train\r2av.py", line 97, in train_epoch
    for sample in r2v_loader:
  File "D:\Anaconda\envs\cup\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\cup\lib\site-packages\torch\utils\data\dataloader.py", line 678, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda\envs\cup\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda\envs\cup\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "H:\rrwnet-main\train\data_vessels.py", line 95, in __getitem__
    assert isinstance(retino, str)
AssertionError

**Comment by j-morano** [comment]
Hello. Thank you so much for pointing out this issue. There was a mistake in the code. I have added a commit solving the issue. Feel free to reopen this issue or open another one if you find any other problems.
